<a href="https://colab.research.google.com/github/fithanesrin/DATASCIENCE/blob/main/datascience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY(Numeric python):
numpy is a python library used for working with arrays
import:import numpy as np

used for mathematical operations

In [ ]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
add=(a+b)
print(add)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])       # mathematial use anu numpy
arr2=np.array([6,7,8,9,10])
result=(arr1+arr2)
print(result)

[ 7  9 11 13 15]


In [ ]:
# indexing
array=[10,20,30,40,50]
print(array[3])

40


In [ ]:
# slicing
# one dimension
arr1=np.array([10,20,30,40,50,60,70,80])
print(arr1.ndim)
print(arr1[1:8:2])


1
[20, 40, 60, 80]


In [ ]:
# 2 dimensinal array
arr1=np.array([[10,20,30,40],[50,60,70,80]])
print(arr1.ndim)




2


In [ ]:
# 3 dimension
arr1=np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(arr1.ndim)

3


In [ ]:
arr1=np.array([[[10,20,30],
                [40,50,60]],

                [[70,80,90],
                [25,35,45]]])
print(arr1[0,1,2])

60


In [ ]:
# one dimension convert to 2dimension/reshape
arr1=np.array([1,2,3,4,5,6,7,8])
arr2=arr1.reshape(2,4)
print(arr1)
print(arr2)
print(arr2.shape)


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
# function-zeros
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
# function ones
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
# function arrange
c=np.arange(1,10)
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#linspace
d=np.linspace(0,20,4)
print(d)


[ 0.          6.66666667 13.33333333 20.        ]


In [ ]:
# random
e=np.random.rand(5)
print(e)

[0.14099845 0.37860255 0.59422994 0.88355918 0.41131539]


In [ ]:
import numpy as np
arr1=np.array([[[10,20,30],
                [40,50,60],
                [70,80,90]]])
print(arr1[0,1,1])




50


In [ ]:

arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2=arr1.reshape(3,4)
print(arr1)
print(arr2)
print(arr2.shape)




[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


PANDAS (panel data system):-

*pandas is an open source library


* used for data cleaning,data analysis,data manipulation and data visualization prepration.

*pandas working with excel sheet or tabular format data.

PANDAS DATA STRUCTURE

Pandas has mainly two type

 1)sereies

 2)data frame

import :import pandas as pd



SERIES:


*Series is an one dimension labelled array

In [ ]:
import pandas as pd
mark=pd.Series([1,2,3,4,5,6])
print(mark)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [ ]:
import pandas as pd
marks=pd.Series([50,79,80,90,],index=["maths","physics","biology","chemistry"])
print(marks)


maths        50
physics      79
biology      80
chemistry    90
dtype: int64


In [ ]:
import pandas as pd
name=pd.Series(["language","computer","commerce","science"],index=["fitha","shifa","shanidha","ardra"])
print(name)


fitha       language
shifa       computer
shanidha    commerce
ardra        science
dtype: object


In [ ]:
import pandas as pd
name=pd.Series(["language","computer","commerce","science"],index=["fitha","shifa","shanidha","ardra"])
print(name["shanidha"])


commerce


DATA FRAME:

1)What is numpy and pandas

ans)numpy (numerical python)is a python library used for working with arrays.

   pandas is a open source library,used for data cleaning,data analysis,data manipulation and data visualization preparation.


2)why do we use numpy and pandas


ans)numpy is used for working with arrays and mathematical operations

pandas is used for data cleaning,data analysis,data manipulation and data visualization preparation

3)what is series

ans) one dimension labelled  array

4)what is the difference between list and numpy array


ans)list can store different data types,slower.
numpy can store elements in same data type,faster.

5)what is indexing and slicing


ans)indexing is accesing single element using position


slicing is accesing multiple element from a sequence


6)create a numpy array contains numbers from 1 to 20


7)create a pandas series with doctors and departments

In [ ]:
# create a numpy arrays contain number 1 to 20
x=np.arange(1,21)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# create a pandas series with doctor and department
import pandas as pd
name=pd.Series(["physycology","cardiology","neurology","ent"],index=["john","madav","megha","leena"])
print(name)


john     physycology
madav     cardiology
megha      neurology
leena            ent
dtype: object
